on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-and-push-docker-image:
    name: Build and Deploy ${{ github.event.repository.name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get the latest tag
        id: get_latest_tag
        run: echo "LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)" >> $GITHUB_ENV

      - name: Login to Github Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push to GitHub Container Registry
        uses: docker/build-push-action@v5
        with:
          context: ./
          build-args: |
            "GIT_TOKEN=${{ secrets.GIT_TOKEN }}"
          tags: ghcr.io/${{ github.repository }}:${{ env.LATEST_TAG }}
          push: true